sudo: false
language: node_js
node_js:
- lts/*
install:
- npm install
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: libero-npm@elifesciences.org
  api_key:
    secure: SHUZsvRU7rju2II2SDHo/HR/dZrHD+2u9auyyHyoJEB2DfXkYN1p4qfCbFBy2+4rrWWboQozg8NYCfolQTwZSUcLIgN4QWa9NVUm4v5TnTP/5vGAIcYeE8v3aKm9rYl8jX7vYrvErjhstJv7UGE29klS5NDHforPrgc1owDS26MMLwjS3/e0a2OLaaeHLCOmZtdDFxMk2EdR2g9Grg9vzUKCp2SMTK4YwwtKp0S4+qi1/leN2ZIQvHWXkKDWJ2Eq1kPxT/s6cuIDHLLwBbTCYL6j/SfM8K1bTvwNkga/0g/4N3YZYcMzUWbhD008jkCoX3zfpEld6duNEA6hcutlX5q28Wcvo20SdbyQHCgK009NvikB/gfNfI2iTCvdns2Et3PLfP228YAY7BePOGYQRnC2zyZ3L+t61TVaq5qZxVXGSoEjA2iKo/LUYFK6NxCj/ASENNTIX2uzXr0LkBU2pEY01ST/7Nl4pD5DcehEtZw1KtZ9vWfPulwrjLkXaQgM6s5lr4dZSsWGhlFXIWE2oL8E6uDi+f1ThnBZ2FTEXcnz89mWVdYkho/afJTF7YxAJMKSulbPIZ3ncuYfvCabDUDzrNxeL4MOfJKePLu58PRrer4AaMA97FmAECf1SX+SRUaXGbzAsH3FeC4209MBZyKHCOMm1jgHyCL1tSbCR8s=
  on:
    tags: true
    branch: master
